CREATE TABLE Object (
  objectId NUMBER(19, 0) NOT NULL,
  iauId char(34) DEFAULT NULL,
  ra_PS FLOAT (24) NOT NULL,
  ra_PS_Sigma float DEFAULT NULL,
  decl_PS FLOAT (24) NOT NULL,
  decl_PS_Sigma float DEFAULT NULL,
  radecl_PS_Cov float DEFAULT NULL,
  htmId20 NUMBER(19, 0) NOT NULL,
  ra_SG FLOAT (24) DEFAULT NULL,
  ra_SG_Sigma float DEFAULT NULL,
  decl_SG FLOAT (24) DEFAULT NULL,
  decl_SG_Sigma float DEFAULT NULL,
  radecl_SG_Cov float DEFAULT NULL,
  raRange float DEFAULT NULL,
  declRange float DEFAULT NULL,
  muRa_PS FLOAT (24) DEFAULT NULL,
  muRa_PS_Sigma float DEFAULT NULL,
  muDecl_PS FLOAT (24) DEFAULT NULL,
  muDecl_PS_Sigma float DEFAULT NULL,
  muRaDecl_PS_Cov float DEFAULT NULL,
  parallax_PS FLOAT (24) DEFAULT NULL,
  parallax_PS_Sigma float DEFAULT NULL,
  canonicalFilterId NUMBER(3, 0) DEFAULT NULL,
  extendedness NUMBER(5, 0) DEFAULT NULL,
  varProb float DEFAULT NULL,
  earliestObsTime FLOAT (24) DEFAULT NULL,
  latestObsTime FLOAT (24) DEFAULT NULL,
  meanObsTime FLOAT (24) DEFAULT NULL,
  flags NUMBER(10, 0) DEFAULT NULL,
  uNumObs NUMBER(10, 0) DEFAULT NULL,
  uExtendedness NUMBER(5, 0) DEFAULT NULL,
  uVarProb float DEFAULT NULL,
  uRaOffset_PS float DEFAULT NULL,
  uRaOffset_PS_Sigma float DEFAULT NULL,
  uDeclOffset_PS float DEFAULT NULL,
  uDeclOffset_PS_Sigma float DEFAULT NULL,
  uRaDeclOffset_PS_Cov float DEFAULT NULL,
  uRaOffset_SG float DEFAULT NULL,
  uRaOffset_SG_Sigma float DEFAULT NULL,
  uDeclOffset_SG float DEFAULT NULL,
  uDeclOffset_SG_Sigma float DEFAULT NULL,
  uRaDeclOffset_SG_Cov float DEFAULT NULL,
  uLnL_PS float DEFAULT NULL,
  uLnL_SG float DEFAULT NULL,
  uFlux_PS float DEFAULT NULL,
  uFlux_PS_Sigma float DEFAULT NULL,
  uFlux_ESG float DEFAULT NULL,
  uFlux_ESG_Sigma float DEFAULT NULL,
  uFlux_Gaussian float DEFAULT NULL,
  uFlux_Gaussian_Sigma float DEFAULT NULL,
  uTimescale float DEFAULT NULL,
  uEarliestObsTime FLOAT (24) DEFAULT NULL,
  uLatestObsTime FLOAT (24) DEFAULT NULL,
  uSersicN_SG float DEFAULT NULL,
  uSersicN_SG_Sigma float DEFAULT NULL,
  uE1_SG float DEFAULT NULL,
  uE1_SG_Sigma float DEFAULT NULL,
  uE2_SG float DEFAULT NULL,
  uE2_SG_Sigma float DEFAULT NULL,
  uRadius_SG float DEFAULT NULL,
  uRadius_SG_Sigma float DEFAULT NULL,
  uFlags NUMBER(10, 0) DEFAULT NULL,
  gNumObs NUMBER(10, 0) DEFAULT NULL,
  gExtendedness NUMBER(5, 0) DEFAULT NULL,
  gVarProb float DEFAULT NULL,
  gRaOffset_PS float DEFAULT NULL,
  gRaOffset_PS_Sigma float DEFAULT NULL,
  gDeclOffset_PS float DEFAULT NULL,
  gDeclOffset_PS_Sigma float DEFAULT NULL,
  gRaDeclOffset_PS_Cov float DEFAULT NULL,
  gRaOffset_SG float DEFAULT NULL,
  gRaOffset_SG_Sigma float DEFAULT NULL,
  gDeclOffset_SG float DEFAULT NULL,
  gDeclOffset_SG_Sigma float DEFAULT NULL,
  gRaDeclOffset_SG_Cov float DEFAULT NULL,
  gLnL_PS float DEFAULT NULL,
  gLnL_SG float DEFAULT NULL,
  gFlux_PS float DEFAULT NULL,
  gFlux_PS_Sigma float DEFAULT NULL,
  gFlux_ESG float DEFAULT NULL,
  gFlux_ESG_Sigma float DEFAULT NULL,
  gFlux_Gaussian float DEFAULT NULL,
  gFlux_Gaussian_Sigma float DEFAULT NULL,
  gTimescale float DEFAULT NULL,
  gEarliestObsTime FLOAT (24) DEFAULT NULL,
  gLatestObsTime FLOAT (24) DEFAULT NULL,
  gSersicN_SG float DEFAULT NULL,
  gSersicN_SG_Sigma float DEFAULT NULL,
  gE1_SG float DEFAULT NULL,
  gE1_SG_Sigma float DEFAULT NULL,
  gE2_SG float DEFAULT NULL,
  gE2_SG_Sigma float DEFAULT NULL,
  gRadius_SG float DEFAULT NULL,
  gRadius_SG_Sigma float DEFAULT NULL,
  gFlags NUMBER(10, 0) DEFAULT NULL,
  rNumObs NUMBER(10, 0) DEFAULT NULL,
  rExtendedness NUMBER(5, 0) DEFAULT NULL,
  rVarProb float DEFAULT NULL,
  rRaOffset_PS float DEFAULT NULL,
  rRaOffset_PS_Sigma float DEFAULT NULL,
  rDeclOffset_PS float DEFAULT NULL,
  rDeclOffset_PS_Sigma float DEFAULT NULL,
  rRaDeclOffset_PS_Cov float DEFAULT NULL,
  rRaOffset_SG float DEFAULT NULL,
  rRaOffset_SG_Sigma float DEFAULT NULL,
  rDeclOffset_SG float DEFAULT NULL,
  rDeclOffset_SG_Sigma float DEFAULT NULL,
  rRaDeclOffset_SG_Cov float DEFAULT NULL,
  rLnL_PS float DEFAULT NULL,
  rLnL_SG float DEFAULT NULL,
  rFlux_PS float DEFAULT NULL,
  rFlux_PS_Sigma float DEFAULT NULL,
  rFlux_ESG float DEFAULT NULL,
  rFlux_ESG_Sigma float DEFAULT NULL,
  rFlux_Gaussian float DEFAULT NULL,
  rFlux_Gaussian_Sigma float DEFAULT NULL,
  rTimescale float DEFAULT NULL,
  rEarliestObsTime FLOAT (24) DEFAULT NULL,
  rLatestObsTime FLOAT (24) DEFAULT NULL,
  rSersicN_SG float DEFAULT NULL,
  rSersicN_SG_Sigma float DEFAULT NULL,
  rE1_SG float DEFAULT NULL,
  rE1_SG_Sigma float DEFAULT NULL,
  rE2_SG float DEFAULT NULL,
  rE2_SG_Sigma float DEFAULT NULL,
  rRadius_SG float DEFAULT NULL,
  rRadius_SG_Sigma float DEFAULT NULL,
  rFlags NUMBER(10, 0) DEFAULT NULL,
  iNumObs NUMBER(10, 0) DEFAULT NULL,
  iExtendedness NUMBER(5, 0) DEFAULT NULL,
  iVarProb float DEFAULT NULL,
  iRaOffset_PS float DEFAULT NULL,
  iRaOffset_PS_Sigma float DEFAULT NULL,
  iDeclOffset_PS float DEFAULT NULL,
  iDeclOffset_PS_Sigma float DEFAULT NULL,
  iRaDeclOffset_PS_Cov float DEFAULT NULL,
  iRaOffset_SG float DEFAULT NULL,
  iRaOffset_SG_Sigma float DEFAULT NULL,
  iDeclOffset_SG float DEFAULT NULL,
  iDeclOffset_SG_Sigma float DEFAULT NULL,
  iRaDeclOffset_SG_Cov float DEFAULT NULL,
  iLnL_PS float DEFAULT NULL,
  iLnL_SG float DEFAULT NULL,
  iFlux_PS float DEFAULT NULL,
  iFlux_PS_Sigma float DEFAULT NULL,
  iFlux_ESG float DEFAULT NULL,
  iFlux_ESG_Sigma float DEFAULT NULL,
  iFlux_Gaussian float DEFAULT NULL,
  iFlux_Gaussian_Sigma float DEFAULT NULL,
  iTimescale float DEFAULT NULL,
  iEarliestObsTime FLOAT (24) DEFAULT NULL,
  iLatestObsTime FLOAT (24) DEFAULT NULL,
  iSersicN_SG float DEFAULT NULL,
  iSersicN_SG_Sigma float DEFAULT NULL,
  iE1_SG float DEFAULT NULL,
  iE1_SG_Sigma float DEFAULT NULL,
  iE2_SG float DEFAULT NULL,
  iE2_SG_Sigma float DEFAULT NULL,
  iRadius_SG float DEFAULT NULL,
  iRadius_SG_Sigma float DEFAULT NULL,
  iFlags NUMBER(10, 0) DEFAULT NULL,
  zNumObs NUMBER(10, 0) DEFAULT NULL,
  zExtendedness NUMBER(5, 0) DEFAULT NULL,
  zVarProb float DEFAULT NULL,
  zRaOffset_PS float DEFAULT NULL,
  zRaOffset_PS_Sigma float DEFAULT NULL,
  zDeclOffset_PS float DEFAULT NULL,
  zDeclOffset_PS_Sigma float DEFAULT NULL,
  zRaDeclOffset_PS_Cov float DEFAULT NULL,
  zRaOffset_SG float DEFAULT NULL,
  zRaOffset_SG_Sigma float DEFAULT NULL,
  zDeclOffset_SG float DEFAULT NULL,
  zDeclOffset_SG_Sigma float DEFAULT NULL,
  zRaDeclOffset_SG_Cov float DEFAULT NULL,
  zLnL_PS float DEFAULT NULL,
  zLnL_SG float DEFAULT NULL,
  zFlux_PS float DEFAULT NULL,
  zFlux_PS_Sigma float DEFAULT NULL,
  zFlux_ESG float DEFAULT NULL,
  zFlux_ESG_Sigma float DEFAULT NULL,
  zFlux_Gaussian float DEFAULT NULL,
  zFlux_Gaussian_Sigma float DEFAULT NULL,
  zTimescale float DEFAULT NULL,
  zEarliestObsTime FLOAT (24) DEFAULT NULL,
  zLatestObsTime FLOAT (24) DEFAULT NULL,
  zSersicN_SG float DEFAULT NULL,
  zSersicN_SG_Sigma float DEFAULT NULL,
  zE1_SG float DEFAULT NULL,
  zE1_SG_Sigma float DEFAULT NULL,
  zE2_SG float DEFAULT NULL,
  zE2_SG_Sigma float DEFAULT NULL,
  zRadius_SG float DEFAULT NULL,
  zRadius_SG_Sigma float DEFAULT NULL,
  zFlags NUMBER(10, 0) DEFAULT NULL,
  yNumObs NUMBER(10, 0) DEFAULT NULL,
  yExtendedness NUMBER(5, 0) DEFAULT NULL,
  yVarProb float DEFAULT NULL,
  yRaOffset_PS float DEFAULT NULL,
  yRaOffset_PS_Sigma float DEFAULT NULL,
  yDeclOffset_PS float DEFAULT NULL,
  yDeclOffset_PS_Sigma float DEFAULT NULL,
  yRaDeclOffset_PS_Cov float DEFAULT NULL,
  yRaOffset_SG float DEFAULT NULL,
  yRaOffset_SG_Sigma float DEFAULT NULL,
  yDeclOffset_SG float DEFAULT NULL,
  yDeclOffset_SG_Sigma float DEFAULT NULL,
  yRaDeclOffset_SG_Cov float DEFAULT NULL,
  yLnL_PS float DEFAULT NULL,
  yLnL_SG float DEFAULT NULL,
  yFlux_PS float DEFAULT NULL,
  yFlux_PS_Sigma float DEFAULT NULL,
  yFlux_ESG float DEFAULT NULL,
  yFlux_ESG_Sigma float DEFAULT NULL,
  yFlux_Gaussian float DEFAULT NULL,
  yFlux_Gaussian_Sigma float DEFAULT NULL,
  yTimescale float DEFAULT NULL,
  yEarliestObsTime FLOAT (24) DEFAULT NULL,
  yLatestObsTime FLOAT (24) DEFAULT NULL,
  ySersicN_SG float DEFAULT NULL,
  ySersicN_SG_Sigma float DEFAULT NULL,
  yE1_SG float DEFAULT NULL,
  yE1_SG_Sigma float DEFAULT NULL,
  yE2_SG float DEFAULT NULL,
  yE2_SG_Sigma float DEFAULT NULL,
  yRadius_SG float DEFAULT NULL,
  yRadius_SG_Sigma float DEFAULT NULL,
  yFlags NUMBER(10, 0) DEFAULT NULL,
  chunkId NUMBER(10, 0) DEFAULT NULL,
  subChunkId NUMBER(10, 0) DEFAULT NULL
  );